import type { NavItem, Role } from "@/types";

export const roleMeta: Record<
  Role,
  { label: string; home: string; color: string; description: string }
> = {
  admin: {
    label: "Administrator",
    home: "/admin/dashboard",
    color: "navy",
    description: "Platform-wide management",
  },
  "school-manager": {
    label: "School Manager",
    home: "/school-manager/dashboard",
    color: "teal",
    description: "School programme oversight",
  },
  teacher: {
    label: "Teacher",
    home: "/teacher/dashboard",
    color: "navy",
    description: "Plan, assign and monitor",
  },
  student: {
    label: "Student",
    home: "/student/dashboard",
    color: "accent",
    description: "Your MathQuest journey",
  },
  parent: {
    label: "Parent",
    home: "/parent/dashboard",
    color: "teal",
    description: "Support your child",
  },
};

export const roleNav: Record<Role, NavItem[]> = {
  admin: [
    { label: "Dashboard", href: "/admin/dashboard", icon: "LayoutDashboard" },
    { label: "Users", href: "/admin/users", icon: "Users" },
    { label: "Schools", href: "/admin/schools", icon: "Building2" },
    { label: "Content", href: "/admin/content", icon: "LibraryBig" },
    { label: "Games", href: "/admin/games", icon: "Gamepad2" },
    { label: "Simulations", href: "/admin/simulations", icon: "FlaskConical" },
    { label: "Books", href: "/admin/books", icon: "BookOpen" },
    { label: "Curriculum", href: "/admin/curriculum", icon: "Map" },
    { label: "Badges", href: "/admin/badges", icon: "Award" },
    { label: "Reports", href: "/admin/reports", icon: "BarChart3" },
    { label: "Announcements", href: "/admin/announcements", icon: "Megaphone" },
    { label: "Settings", href: "/admin/settings", icon: "Settings" },
    { label: "Profile", href: "/admin/profile", icon: "UserCog" },
  ],
  "school-manager": [
    { label: "Dashboard", href: "/school-manager/dashboard", icon: "LayoutDashboard" },
    { label: "Teachers", href: "/school-manager/teachers", icon: "GraduationCap" },
    { label: "Classes", href: "/school-manager/classes", icon: "Users" },
    { label: "Students", href: "/school-manager/students", icon: "Baby" },
    { label: "Parents", href: "/school-manager/parents", icon: "Heart" },
    { label: "Curriculum Coverage", href: "/school-manager/curriculum-coverage", icon: "Map" },
    { label: "Reports", href: "/school-manager/reports", icon: "BarChart3" },
    { label: "Teacher Activity", href: "/school-manager/teacher-activity", icon: "Activity" },
    { label: "Announcements", href: "/school-manager/announcements", icon: "Megaphone" },
    { label: "Settings", href: "/school-manager/settings", icon: "Settings" },
  ],
  teacher: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: "LayoutDashboard" },
    { label: "Classes", href: "/teacher/classes", icon: "Users" },
    { label: "Students", href: "/teacher/students", icon: "Baby" },
    { label: "Library", href: "/teacher/library", icon: "LibraryBig" },
    { label: "Games", href: "/teacher/games", icon: "Gamepad2" },
    { label: "Simulations", href: "/teacher/simulations", icon: "FlaskConical" },
    { label: "Books", href: "/teacher/books", icon: "BookOpen" },
    { label: "Assignments", href: "/teacher/assignments", icon: "ClipboardList" },
    { label: "Quest Paths", href: "/teacher/quest-paths", icon: "Route" },
    { label: "Progress", href: "/teacher/progress", icon: "TrendingUp" },
    { label: "Reports", href: "/teacher/reports", icon: "BarChart3" },
    { label: "Resources", href: "/teacher/resources", icon: "FolderOpen" },
    { label: "Messages", href: "/teacher/messages", icon: "MessageSquare" },
    { label: "Settings", href: "/teacher/settings", icon: "Settings" },
  ],
  student: [
    { label: "Dashboard", href: "/student/dashboard", icon: "Home" },
    { label: "My Quest", href: "/student/my-quest", icon: "Route" },
    { label: "Today's Quest", href: "/student/todays-quest", icon: "Sparkles" },
    { label: "Games", href: "/student/games", icon: "Gamepad2" },
    { label: "Simulations", href: "/student/simulations", icon: "FlaskConical" },
    { label: "Books", href: "/student/books", icon: "BookOpen" },
    { label: "Assignments", href: "/student/assignments", icon: "ClipboardList" },
    { label: "Achievements", href: "/student/achievements", icon: "Award" },
    { label: "Progress", href: "/student/progress", icon: "TrendingUp" },
    { label: "Profile", href: "/student/profile", icon: "Smile" },
  ],
  parent: [
    { label: "Dashboard", href: "/parent/dashboard", icon: "LayoutDashboard" },
    { label: "Children", href: "/parent/children", icon: "Users" },
    { label: "Progress", href: "/parent/progress", icon: "TrendingUp" },
    { label: "Assignments", href: "/parent/assignments", icon: "ClipboardList" },
    { label: "Achievements", href: "/parent/achievements", icon: "Award" },
    { label: "Home Learning", href: "/parent/home-learning", icon: "House" },
    { label: "Messages", href: "/parent/messages", icon: "MessageSquare" },
    { label: "Settings", href: "/parent/settings", icon: "Settings" },
  ],
};
